/* Prueba automática de punta a punta (solo en la versión de prueba). Recorre A → C → D → E → F. */
window.__FAST = true;
(async () => {
  const R = []; const box = document.createElement('pre');
  box.style.cssText = 'position:fixed;left:8px;top:8px;z-index:99;max-width:46vw;max-height:96vh;overflow:auto;margin:0;padding:8px;background:#000c;color:#9f9;font:11px/1.35 monospace;white-space:pre-wrap';
  document.body.appendChild(box);
  const show = () => { box.textContent = R.join('\n'); };
  const ok = (c, m) => { R.push((c ? 'OK  ' : 'FAIL') + ' ' + m); show(); return c; };
  const w = ms => new Promise(r => setTimeout(r, ms));
  const until = async (f, ms = 4000) => { const t = Date.now(); while (Date.now() - t < ms) { try { if (f()) return true; } catch (e) {} await w(40); } return false; };
  const el = (act, v) => [...document.querySelectorAll(`[data-act="${act}"]`)].find(x => v == null || x.dataset.v === String(v));
  const click = async (act, v) => { await until(() => el(act, v), 3000); const x = el(act, v); if (!x) { ok(false, `no encuentro ${act}=${v}`); return false; } x.click(); await w(60); return true; };
  const okBtn = async () => { await until(() => document.querySelector('form[data-sel] .s-send')); document.querySelector('form[data-sel] .s-send').click(); await w(80); };
  const okVisible = () => !!document.querySelector('form[data-ok]:not([data-texto]) .s-send .s-ok') && getComputedStyle(document.querySelector('form[data-ok] .s-send .s-ok')).display !== 'none';
  const chip = v => click(UI.view === 'grupo' ? 'reply' : 'paso', v);
  const send = async t => { const f = document.querySelector('form[data-act="enviar"]'); f.m.value = t; f.requestSubmit(); await w(80); };
  try {
    LocalDB.wipe();
    const STOP = window.__STOP_AT; const stop = k => { if (STOP === k) { box.style.display = 'none'; throw 'stop'; } };
    await until(() => Yo.doc && UI.view === 'sintonia' && S1.st.step === 'A0' && el('paso', 'Quiero organizar'), 8000);
    ok(S1.st.step === 'A0', 'A0 entrada visible');
    ok(!document.querySelector('form[data-ok]'), 'Por defecto el botón es el ícono de enviar'); await chip('Quiero organizar'); await until(() => S1.st.step === 'A1' && el('paso', 'Amigos'));
    await chip('Amigos'); await until(() => S1.st.step === 'A2' && el('paso', '4 a 5'));
    await chip('4 a 5'); await until(() => S1.st.step === 'A3a' && el('paso', 'Ninguno'));
    await chip('Ninguno'); await until(() => S1.st.step === 'A3b' && el('paso', 'Yo, siempre'));
    await chip('Yo, siempre'); await until(() => S1.st.step === 'A4' && el('paso-listo'));
    await until(() => okVisible()); ok(okVisible(), 'A4 dial: OK visible antes de mover el slider'); const r = document.querySelector('input[type=range][data-act=dial]'); r.value = 2; r.dispatchEvent(new Event('input', { bubbles: true }));
    await okBtn(); await until(() => S1.st.step === 'A5a' && el('multi', 'Café'));
    ok(S1.st.ans.energia === 2, 'A4 energía = 2');
    await click('multi', 'Café'); await click('multi', 'Algo cultural'); await okBtn();
    await until(() => S1.st.step === 'A5b' && el('band', 'tarde'));
    ok(String(S1.st.ans.antojos) === 'Café,Algo cultural', 'A5 antojos');
    await click('band', 'tarde'); await until(() => S1.st.step === 'A5c' && el('paso', 'Parche del domingo'));
    await chip('Parche del domingo'); await until(() => S1.st.step === 'A6a' && el('toggle', null));
    await click('toggle'); const tg = [...document.querySelectorAll('[data-act=toggle]')].find(x => x.dataset.k === 'nom'); tg.click(); await w(60);
    stop('A6');
    ok(okVisible(), 'Enviar dice OK tras elegir (confirmación)'); const fm = document.querySelector('form[data-act=enviar]'); fm.m.value = 'hola'; fm.m.dispatchEvent(new Event('input', { bubbles: true })); ok(!okVisible(), 'Al escribir vuelve el ícono de enviar'); fm.m.value = ''; fm.m.dispatchEvent(new Event('input', { bubbles: true })); await okBtn(); await until(() => S1.st.step === 'A6b');
    ok(Yo.doc.consent.nom === true && Yo.doc.consent.wa === true, 'A6 consentimiento guardado (wa, nom)');
    await send('Caro'); await until(() => S1.st.step === 'A7' && S1.st.pid, 5000);
    const pid = S1.st.pid; ok(!!pid && Yo.doc.nombre === 'Caro', 'A7 parche creado ' + pid);
    await until(() => el('copiar'));
    ok(!!el('copiar'), 'A7 invitación con código');
    await chip('Abrir el chat del grupo'); await until(() => UI.view === 'grupo' && Grupo.listo && Grupo.yo, 5000);
    ok(Grupo.p && Grupo.p.stage === 'reclutando' && Grupo.N === 4, 'B4/A7 grupo en reclutamiento, quórum 4');
    ok(document.querySelector('.s-station[data-state=searching]') != null, 'Cabecera: buscando señal');
    for (let i = 0; i < 3; i++) { await Team.accion('bot'); await w(150); }
    await until(() => Grupo.p.stage === 'votacion', 4000);
    ok(Grupo.p.stage === 'votacion' && Grupo.p.opciones.length === 3, 'C1 votación abierta con 3 opciones');
    await until(() => document.querySelector('.s-vote-card')); ok(!!document.querySelector('.s-vote-card'), 'C1 tarjeta de votación');
    await click('pick', 2); ok(Grupo.sel === 2, 'Cuadrante: elegir opción 2');
    stop('C1');
    await click('votar', 2); await until(() => Grupo.miVoto && Grupo.miVoto.opcion === 2);
    ok(Grupo.miVoto && Grupo.miVoto.opcion === 2, 'C2 voto registrado');
    await until(() => Grupo.mensajes.some(m => (m._id || '').startsWith('ack-')));
    ok(Grupo.mensajes.some(m => (m._id || '').startsWith('ack-')), 'C2 Sintonía confirma el voto');
    await chip('Cambiar mi voto'); await until(() => !Grupo.miVoto);
    ok(!Grupo.miVoto, 'Cambiar mi voto borra el voto');
    await click('ninguna'); await until(() => Grupo.miVoto && Grupo.miVoto.opcion === 'ninguna');
    ok(document.querySelector('[data-v="Muy lejos"]') != null, 'C3 motivos de «Ninguna me sirve»');
    await chip('Muy caro'); await until(() => Grupo.miVoto && Grupo.miVoto.motivo === 'Muy caro');
    ok(Grupo.miVoto.motivo === 'Muy caro', 'C3 motivo guardado (anónimo)');
    const otros = Grupo.mensajes.filter(m => m.solo === Me.uid).length; ok(otros >= 2, 'C3 mensajes del veto solo visibles para mí');
    await chip('Cambiar mi voto'); await until(() => !Grupo.miVoto); await click('pick', 1); await click('votar', 1);
    await Team.accion('botsvotan'); await until(() => ['resolviendo', 'fijado'].includes(Grupo.p.stage), 4000);
    ok(['resolviendo', 'fijado'].includes(Grupo.p.stage), 'C4 resolviendo (válvulas)');
    await until(() => Grupo.p.stage === 'fijado', 5000);
    ok(Grupo.p.stage === 'fijado' && Grupo.p.plan, 'C5 plan fijado: ' + (Grupo.p.plan && Grupo.p.plan.titulo));
    ok(!!document.querySelector('.s-plan-list'), 'C5 lista del plan');
    stop('C5');
    ok(!!el('apuntar', 'si'), 'C5 CTA «¿Te apuntas?» en el plan fijado'); await click('apuntar', 'si'); await until(() => Grupo.yo.asistencia === 'si'); ok(Grupo.yo.asistencia === 'si', 'C5 me apunto');
    await Team.accion('c6'); await until(() => el('reply', 'Ahí estaré')); await chip('Ahí estaré'); await until(() => Grupo.yo.confirmaD1 === true);
    ok(Grupo.yo.confirmaD1 === true && !!document.querySelector('.s-display'), 'C6 recordatorio y confirmación');
    await Team.accion('c7'); await until(() => Grupo.p.stage === 'encurso'); await until(() => Grupo.mensajes.some(m => m._id === 'dia')); ok(Grupo.mensajes.find(m => m._id === 'dia').t.startsWith('¡Es hoy, es hoy!'), 'C7 «¡Es hoy, es hoy!»'); await chip('¡Llegué!'); await until(() => Grupo.yo.llego);
    ok(Grupo.yo.llego === true, 'C7 día del plan: llegué');
    await Team.accion('d'); await until(() => S1.st.flow === 'D', 4000);
    ok(S1.st.flow === 'D' && S1.st.step === 'D1', 'D1 sobremesa privada iniciada');
    UI.ir('sintonia'); await until(() => document.querySelector('.e-dial input:not([disabled])') && document.querySelector('form[data-sel]')); ok(okVisible(), 'Dial: OK desde el inicio (el slider no lo activa)'); ok(!!document.querySelector('.e-scale .e-marks'), 'Dial de energía con riel y marcas'); await okBtn();
    await until(() => S1.st.step === 'D2a' && el('paso', '4')); await chip('4');
    await until(() => S1.st.step === 'D2b' && el('paso', 'La conversación')); await chip('La conversación');
    await until(() => S1.st.step === 'D3a' && el('paso', 'Cómodo')); await chip('Cómodo');
    await until(() => S1.st.step === 'D3b' && el('paso', 'Sí, pronto')); await chip('Sí, pronto');
    await until(() => S1.st.step === 'D4' && el('paso', 'No sé')); ok(S1.st.step === 'D4', 'D4 disposición a pagar (organiza)'); await chip('No sé');
    await until(() => S1.st.step === 'D5' && Yo.doc.sobremesa[pid]); ok(!!Yo.doc.sobremesa[pid], 'D5 sobremesa guardada');
    const sm = await Store.get(`parches/${pid}/sobremesa/${Me.uid}`); ok(sm && sm.satisfaccion === 4 && sm.dpp === 'No sé', 'D datos en la base');
    await chip('Ir al grupo'); await until(() => UI.view === 'grupo'); await until(() => el('repetir', 'si')); ok(!!el('repetir', 'si'), 'D5 «¿Repetimos con este parche?» en vez de compartir contacto'); await click('repetir', 'si'); await until(() => Grupo.yo.repetir === 'si'); ok(Grupo.yo.repetir === 'si', 'D5 intención de reencuentro guardada'); await chip('Guardar en mis parches'); await until(() => Yo.doc.guardados.length === 1);
    ok(Yo.doc.guardados.length === 1, 'D5 parche guardado');
    UI.ir('mis'); await w(200); stop('E1'); ok(!!document.querySelector('.s-presets .s-preset[data-state="saved"], .s-presets .s-preset[data-state="active"]'), 'E1 Mis sintonías con parche guardado');
    UI.ir('perfil'); await w(50); UI.ir('humano'); await w(50); document.querySelector('[data-act=back]').click(); await w(80); ok(UI.view === 'perfil', 'Volver regresa a la pantalla anterior'); UI.ir('grupo', pid); await w(80); UI.atras(); await w(50); ok(UI.view === 'humano' || UI.view === 'perfil', 'Volver desde el grupo'); UI.hist = []; UI.ir('grupo', pid); UI.hist = []; UI.atras(); await w(50); ok(UI.view === 'chats', 'Volver sin historial va a Chats');
    UI.ir('perfil'); await w(150); const pn = [...document.querySelectorAll('[data-act=toggle]')].find(x => x.dataset.k === 'p-mej'); pn.click(); await until(() => Yo.doc.consent.mej === true); ok(Yo.doc.consent.mej === true, 'E3 permiso cambiado');
    await w(400); const mm = await Store.get(`parches/${pid}/miembros/${Me.uid}`); ok(mm && mm.consent.mej === true, 'E3 permiso propagado al parche');
    UI.ir('humano'); await w(100); await send('No me llegó el enlace'); await until(() => Soporte.msgs.length === 1); ok(Soporte.msgs.length === 1, 'E4 mensaje al equipo');
    await Soporte.escribir(Me.uid, 'Hola, ya te lo reenvío', 'eq', 'Equipo'); await until(() => Soporte.msgs.length === 2); ok(Soporte.msgs.length === 2, 'E4 respuesta del equipo');
    UI.ir('grupo', pid); await until(() => Grupo.listo);
    Store.falla.offline = true; await send('Mensaje sin señal'); ok(Grupo.cola.length === 1, 'F1 mensaje en cola sin conexión');
    Store.falla.offline = false; await Grupo.vaciarCola(); ok(Grupo.cola.length === 0, 'F1 cola enviada al volver');
    Store.falla.envio = true; await send('Este falla'); ok(!!Grupo.errorEnvio, 'F2 error al enviar'); await click('reintentar'); await until(() => !Grupo.errorEnvio); ok(!Grupo.errorEnvio, 'F2 reintento');
    await send('SALIR'); await until(() => UI.sheet); ok(UI.sheet, 'F4 hoja de salir');
    await click('salir-si'); await until(() => UI.view === 'mis'); const gone = await Store.get(`parches/${pid}/miembros/${Me.uid}`); ok(!gone && !Yo.doc.parches.includes(pid), 'F4 salió y se borraron sus datos');
    // F3: nuevo parche sin quórum
    const p2 = await Grupo.crear({ nombreParche: 'Prueba F3', quorum: 4, antojos: ['Café'], franja: 'tarde' }); UI.ir('grupo', p2); await until(() => Grupo.listo && Grupo.yo);
    await Team.accion('bot'); await w(200); await Team.accion('plazo'); await until(() => Grupo.p.stage === 'sinquorum', 4000); ok(Grupo.p.stage === 'sinquorum', 'F3 sin quórum');
    await chip('Seguir con los que estamos'); await until(() => Grupo.p.stage === 'votacion', 4000); ok(Grupo.p.stage === 'votacion' && Grupo.N === 2, 'F3 seguir con los que están → votación');
  } catch (e) { if (e === 'stop') return; ok(false, 'excepción: ' + (e && e.stack || e)); }
  const fails = R.filter(x => x.startsWith('FAIL')).length;
  R.unshift(`== Prueba E3: ${R.length - fails}/${R.length} OK ==`); show(); document.title = fails ? 'FALLA ' + fails : 'TODO OK';
})();
