/* ── 04 · Piezas del DS 3.0 (mismos nombres que en Figma) ─────────────────── */
const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const root = document.documentElement, mqDark = matchMedia('(prefers-color-scheme: dark)');
const isDark = () => root.dataset.theme ? root.dataset.theme === 'dark' : mqDark.matches;
let AV_BASE = 'avatares/', AV_SUF = '.png'; // la compilación para GitHub los cambia a ../ds-3.0/assets/avatares/ y _48@2x.png
const avSrc = id => `${AV_BASE}${id}_${isDark() ? 'oscuro' : 'claro'}${AV_SUF}`;
const swapAvatars = () => document.querySelectorAll('img[data-avatar]').forEach(i => { const s = avSrc(i.dataset.avatar); if (i.getAttribute('src') !== s) i.setAttribute('src', s); });

const I = {
  'arrow-left': '<path d="M19 12H5"/><path d="M11 6L5 12L11 18"/>', 'arrow-right': '<path d="M5 12H19"/><path d="M13 6L19 12L13 18"/>',
  users: '<path d="M9 12C10.93 12 12.5 10.43 12.5 8.5C12.5 6.57 10.93 5 9 5C7.07 5 5.5 6.57 5.5 8.5C5.5 10.43 7.07 12 9 12Z"/><path d="M3 19.5C3.6 16.3 6 14.5 9 14.5C12 14.5 14.4 16.3 15 19.5"/><path d="M15.5 5.3C16.76 5.86 17.58 7.12 17.58 8.5C17.58 9.88 16.76 11.14 15.5 11.7"/><path d="M17.5 14.8C19.3 15.4 20.5 17 21 19.5"/>',
  user: '<path d="M12 12C14.21 12 16 10.21 16 8C16 5.79 14.21 4 12 4C9.79 4 8 5.79 8 8C8 10.21 9.79 12 12 12Z"/><path d="M4.5 20C5.3 16.6 8.3 14.5 12 14.5C15.7 14.5 18.7 16.6 19.5 20"/>',
  chat: '<path d="M6.5 4C5.12 4 4 5.12 4 6.5V14.5C4 15.6 4.6 16.6 5.5 17V20.5L10 17H17.5C18.88 17 20 15.88 20 14.5V6.5C20 5.12 18.88 4 17.5 4H6.5Z"/>',
  calendar: '<path d="M17.5 5.5H6.5C5.12 5.5 4 6.62 4 8V17.5C4 18.88 5.12 20 6.5 20H17.5C18.88 20 20 18.88 20 17.5V8C20 6.62 18.88 5.5 17.5 5.5Z"/><path d="M4 10H20"/><path d="M8.5 3.5V7.5"/><path d="M15.5 3.5V7.5"/>',
  clock: '<path d="M12 20.5C16.69 20.5 20.5 16.69 20.5 12C20.5 7.31 16.69 3.5 12 3.5C7.31 3.5 3.5 7.31 3.5 12C3.5 16.69 7.31 20.5 12 20.5Z"/><path d="M12 7.5V12L15 14"/>',
  check: '<path d="M5 12.5L9.5 17L19 7.5"/>', 'chevron-right': '<path d="M9 6L15 12L9 18"/>', x: '<path d="M6 6L18 18"/><path d="M18 6L6 18"/>',
  refresh: '<path d="M19.5 12C19.5 16.14 16.14 19.5 12 19.5C7.86 19.5 4.5 16.14 4.5 12C4.5 7.86 7.86 4.5 12 4.5C14.07 4.5 15.94 5.34 17.3 6.7"/><path d="M19.5 4.5V9H15"/>',
  alert: '<path d="M20.5 19.5L12 4.5L3.5 19.5H20.5Z"/><path d="M12 10V14.5"/><path d="M12 17V17.5"/>',
  copy: '<path d="M17.5 8H10.5C9.12 8 8 9.12 8 10.5V17.5C8 18.88 9.12 20 10.5 20H17.5C18.88 20 20 18.88 20 17.5V10.5C20 9.12 18.88 8 17.5 8Z"/><path d="M16 8V6.5C16 5.12 14.88 4 13.5 4H6.5C5.12 4 4 5.12 4 6.5V13.5C4 14.88 5.12 16 6.5 16H8"/>',
  plus: '<path d="M12 5V19"/><path d="M5 12H19"/>', wrench: '<path d="M14.5 6.5a4 4 0 0 0-5.3 5.3L4.5 16.5l3 3 4.7-4.7a4 4 0 0 0 5.3-5.3l-2.5 2.5-2.5-.5-.5-2.5 2.5-2.5z"/>',
};
const ic = (n, s = 24) => `<svg class="s-icon" width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${I[n] || ''}</svg>`;
const av = (voz = 'quinto') => { const [id, nom] = VOZ[voz] || VOZ.quinto; return `<img data-avatar="${id}" src="${avSrc(id)}" alt="${nom}, anfitrión de Sintonía" width="40" height="42">`; };

const P = {
  head: h => {
    const st = h.station ? `<div class="s-station" data-state="${h.station.state}" aria-live="polite"><span><i></i>${esc(h.station.text)}</span></div>` : '<div class="s-scale" aria-hidden="true"></div>';
    const sub = h.escribiendo ? `<b>${esc(h.escribiendo)}</b><span class="s-wave"><svg viewBox="0 0 30 8" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M0 4 Q 3.75 0 7.5 4 T 15 4 T 22.5 4 T 30 4"/></svg>escribiendo…</span>` : esc(h.sub || '');
    const left = h.grupo ? `<span class="s-group-avatar">${ic('users', 18)}</span>` : `<figure class="s-cathedral" ${h.alAire ? 'data-on-air' : ''}>${av(h.voz)}</figure>`;
    return `<header class="s-chat-header"><div class="s-bar"><button class="s-back" aria-label="Volver" data-act="back">${ic('arrow-left')}</button>${left}<div class="s-title"><h1>${esc(h.titulo)}</h1><p>${sub}</p></div><button class="s-human" data-size="header" data-act="humano" ${h.humanoLive ? 'data-state="live"' : ''}><span class="s-grip" aria-hidden="true"></span><span>${h.humanoLive ? 'En línea<br>con alguien' : 'Habla con<br>un humano'}</span></button></div>${st}</header>`;
  },
  sep: t => `<div class="s-date" role="separator">${esc(t)}</div>`,
  ai: (t, h, voz) => `<article class="s-message" data-author="ai"><figure class="s-cathedral">${av(voz)}</figure><div class="s-bubble"><header>Sintonía <span class="s-ia">IA</span></header><p>${esc(t)}</p><time>${esc(h)}</time></div></article>`,
  member: (n, t, h) => `<article class="s-message" data-author="member"><span class="s-initial" aria-hidden="true">${esc((n || '?')[0].toUpperCase())}</span><div class="s-bubble"><header>${esc(n)}</header><p>${esc(t)}</p><time>${esc(h)}</time></div></article>`,
  me: (t, h, estado = 'ok') => `<article class="s-message" data-author="me"${estado === 'err' ? ' data-error' : ''}><div class="s-bubble"><p>${esc(t)}</p><time>${esc(h)} ${estado === 'ok' ? '✓✓ <span class="sr-only">Enviado</span>' : estado === 'cola' ? '· en cola' : estado === 'err' ? '· no se envió' : '…'}</time></div></article>`,
  att: html => `<div class="s-attach">${html}</div>`,
  chips: (arr, act = 'reply') => `<div class="s-quick-replies">${arr.map(c => { const [t, on, a, v] = Array.isArray(c) ? c : [c]; return `<button class="s-quick-reply" aria-pressed="${!!on}" data-act="${a || act}" data-v="${esc(v == null ? t : v)}">${esc(t)}</button>`; }).join('')}</div>`,
  toggle: (t, on, key, dis) => `<button class="s-toggle" role="switch" aria-checked="${!!on}" data-act="toggle" data-k="${key}"${dis ? ' disabled' : ''}><span>${esc(t)}</span><span class="s-lever-switch" aria-hidden="true"></span></button>`,
  band: (sel, dis) => `<div class="s-band" role="radiogroup" aria-label="Franja">${FRANJAS.map(f => `<button role="radio" aria-checked="${f.id === sel}" data-act="band" data-v="${f.id}"${dis ? ' disabled' : ''}><b>${f.b}</b><small>${f.s}</small></button>`).join('')}</div>`,
  energy: (q, v, dis) => { const f = (v - 1) / 4; return `<div class="s-energy-dial e-dial"><div class="e-head"><span class="t-label-field">${esc(q)}</span><b data-e="val">${ENERGIA[v - 1]}</b></div><div class="e-scale" style="--f:${f}" data-e="scale"><span class="e-marks" aria-hidden="true">${[1, 2, 3, 4, 5].map(k => `<i${k <= v ? ' data-on' : ''}></i>`).join('')}</span><input type="range" min="1" max="5" step="1" value="${v}" data-act="dial" aria-label="${esc(q)}" aria-valuetext="${ENERGIA[v - 1]}, ${v} de 5"${dis ? ' disabled' : ''}></div><div class="e-labels" aria-hidden="true"><span>Agotado</span><span>A tope</span></div></div>`; },
  apuntas: est => `<div class="e-rsvp"><strong>¿Te apuntas?</strong><div class="s-actions">${est === 'si' ? `<p class="t-body-small">Te apuntaste. ¡Nos vemos!</p><button class="s-button" data-style="secondary" data-size="sm" data-act="apuntar" data-v="no">Ya no puedo</button>` : est === 'no' ? `<p class="t-body-small">Avisaste que no puedes.</p><button class="s-button" data-size="sm" data-act="apuntar" data-v="si">Sí puedo</button>` : `<button class="s-button" data-act="apuntar" data-v="si">Me apunto</button><button class="s-button" data-style="secondary" data-act="apuntar" data-v="no">No puedo</button>`}</div></div>`,
  reencuentro: est => `<div class="e-rsvp"><strong>¿Repetimos con este parche?</strong><p class="t-body-small" style="color:var(--color-text-secondary)">Solo lo ve Sintonía; nos ayuda a proponerles el siguiente plan.</p><div class="s-actions">${[['si', 'Sí, repitamos'], ['tal-vez', 'Tal vez'], ['no', 'Ahora no']].map(([k, t]) => `<button class="s-quick-reply" aria-pressed="${est === k}" data-act="repetir" data-v="${k}">${t}</button>`).join('')}</div></div>`,
  gauge: (n, N) => { const f = N ? Math.min(n / N, 1) : 0; const a = (-160 + 140 * f) * Math.PI / 180; const x = 38 + 24 * Math.cos(a), y = 40 + 24 * Math.sin(a); return `<svg class="s-gauge" viewBox="0 0 76 46" aria-hidden="true"><path d="M8 40 A30 30 0 0 1 68 40" fill="none" stroke="var(--color-text-secondary)" stroke-width="1.5"/><path d="M60 22 A30 30 0 0 1 68 40" fill="none" stroke="var(--color-signal-live)" stroke-width="3.5"/><line x1="38" y1="40" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}" stroke="var(${f >= 1 ? '--color-signal-locked' : '--color-text-accent-strong'})" stroke-width="2" stroke-linecap="round"/><circle cx="38" cy="40" r="4" fill="var(--color-text-primary)"/></svg>`; },
  quorum: (n, N) => { const f = N - n; return `<div class="s-quorum" role="progressbar" aria-valuenow="${n}" aria-valuemax="${N}" aria-valuetext="${n} de ${N}" ${n >= N ? 'data-complete' : ''}>${P.gauge(n, N)}<span><b>QUÓRUM ${n} DE ${N}</b><small>${f <= 0 ? 'Parche en sintonía' : f === 1 ? 'Falta 1 persona' : `Faltan ${f} personas`}</small></span></div>`; },
  vote: (ops, sel, opts = {}) => {
    const k = Math.max(1, Math.min(3, sel || 1));
    const rail = `<div class="s-dial-vote" role="slider" aria-label="Opción elegida" aria-valuemin="1" aria-valuemax="3" aria-valuenow="${k}" tabindex="${opts.cerrada ? -1 : 0}" data-act="${opts.cerrada ? '' : 'rail'}"><div class="s-rail" style="--fill:${[7, 50, 93][k - 1]}%"><i></i><b></b><ol>${[1, 2, 3].map(j => `<li ${j === k ? 'aria-current="true"' : ''}>${j}</li>`).join('')}</ol></div><output>${opts.fijo ? 'FIJO' : k + '/3'}</output></div>`;
    const rows = ops.map((o, i) => `<button class="s-station-option" role="radio" aria-checked="${i + 1 === k}" data-act="pick" data-v="${i + 1}"${opts.cerrada ? ' disabled' : ''}><span class="s-num">${i + 1}</span><span><strong>${esc(o.titulo)}</strong><small>${esc(detalleOpcion(o))}</small></span></button>`).join('');
    const acc = opts.cerrada ? `<div class="s-actions"><p class="t-body-small" style="color:var(--color-text-secondary)">${esc(opts.nota || 'Votación cerrada')}</p></div>`
      : opts.votado ? `<div class="s-actions"><p class="t-body-small" style="color:var(--color-text-secondary)">${esc(opts.votado)}</p></div>`
      : `<div class="s-actions"><button class="s-button" data-block data-act="votar" data-v="${k}">Votar por la ${k}</button><div class="s-links"><button class="s-link" data-act="reply" data-v="Ajustar hora">Ajustar hora</button><button class="s-link" data-tone="danger" data-act="ninguna">Ninguna me sirve</button></div></div>`;
    return `<div class="s-vote-card">${rail}${rows}${acc}</div>`;
  },
  plan: (pl, st) => {
    const done = st === 'done', cur = st === 'cur'; let t = pl.fecha;
    const rows = pl.paradas.map(([n, d], i) => { const r = [String(i + 1).padStart(2, '0'), n, horaMsg(t), durTxt(d)]; t += d * 60000; return r; });
    const tot = pl.paradas.reduce((a, p) => a + p[1], 0);
    const w = pl.paradas.map(p => Math.max(p[1], 15));
    return `<section class="s-plan-list" ${done ? 'data-state="done"' : ''}><header><span class="s-control">${ic(done ? 'refresh' : 'clock', 18)}</span><span><b>Lista del plan</b><small>${esc(fechaCorta(pl.fecha))} · ${done ? 'terminado' : `${pl.paradas.length} paradas · ${durTxt(tot)}`}</small></span></header><div class="s-progress" aria-hidden="true">${w.map((x, i) => `<i style="--w:${x};--p:${done ? 100 : cur && i === 0 ? 50 : 0}%"></i>`).join('')}</div><ol>${rows.map(([n, tt, h, d], i) => `<li ${cur && i === 0 ? 'aria-current="step"' : ''}>${done ? ic('check', 18) : `<em>${n}</em>`}<span><strong>${esc(tt)}</strong>${esc(h)}</span>${esc(d)}</li>`).join('')}</ol>${done ? '' : '<small class="t-caption-default" style="color:var(--color-text-secondary)">Se avisa al grupo antes de cada parada</small>'}</section>`;
  },
  display: (type, label, value, unit) => `<time class="s-display" data-type="${type}"><span><small>${esc(label)}</small><b data-ghost="${esc(String(value).replace(/\d/g, '8'))}">${esc(value)}</b></span><small>${esc(unit)}</small></time>`,
  valves: p => `<div class="s-valves" aria-live="polite"><span class="s-tubes" aria-hidden="true">${[0, 1, 2].map(i => `<i ${i < p ? 'data-on' : ''}></i>`).join('')}</span><span><strong>${['Leyendo lo que contaron…', 'Buscando lugares cerca…', 'Armando la decisión…'][p - 1]}</strong><small>Paso ${p} de 3</small></span></div>`,
  invite: (code, link) => `<div class="s-invite"><b>Invita a tu parche</b><code>${esc(link || 'Código: ' + code)}</code><p class="t-caption-default" style="color:var(--color-text-secondary)">Código del parche: <b class="mono">${esc(code)}</b>. Quien lo abra entra como invitado.</p><button class="s-button" data-style="secondary" data-size="sm" data-act="copiar" data-v="${esc(link || code)}">${ic('copy', 16)}Copiar</button></div>`,
  banner: (t, b, type = 'error') => `<div class="s-banner" data-type="${type}" role="${type === 'error' ? 'alert' : 'status'}">${ic(type === 'error' ? 'alert' : 'clock')}<div><strong>${esc(t)}</strong>${esc(b)}</div></div>`,
  sheet: () => `<div class="s-sheet" role="dialog" aria-modal="true" aria-labelledby="h-borrar"><small>Salir y borrar</small><h2 id="h-borrar">¿Seguro que quieres salir?</h2><p class="t-body-small" style="color:var(--color-text-secondary)">Esto borra tus respuestas de este plan y te saca del grupo. No se puede deshacer.</p><div class="s-actions"><button class="s-button" data-style="secondary" data-act="salir-no">Mejor no</button><button class="s-button" data-style="danger" data-act="salir-si">Sí, salir y borrar</button></div></div>`,
  phead: (t, s, ini) => `<header class="s-panel-head"><div><h1>${esc(t)}</h1><p>${esc(s)}</p></div><span class="s-me">${esc(ini || 'Tú')}</span></header>`,
  tabs: (a, c) => `<div class="s-tabs" role="tablist">${[['Todas', c[0]], ['Por mí', c[1]], ['Me invitaron', c[2]]].map(([t, n], i) => `<button role="tab" aria-selected="${i === a}" data-act="tab" data-v="${i}">${t}<span>${n}</span></button>`).join('')}</div>`,
  row: (st, d, h, n, e, a, pid) => `<button class="s-tuning-row" data-state="${st}" data-act="abrir" data-v="${esc(pid)}"><span class="s-when"><small>${esc(d)}</small><b>${esc(h)}</b></span><span><strong>${esc(n)}</strong><small><i></i>${esc(e)}</small><small>${esc(a)}</small></span>${ic('chevron-right', 20)}</button>`,
  presets: list => `<section class="s-presets"><header>Mis parches <span>${list.length} de 4</span></header><ul>${[0, 1, 2, 3].map(i => { const g = list[i]; return `<li><button class="s-preset" data-state="${g ? (g.activo ? 'active' : 'saved') : 'empty'}" ${g ? `data-act="abrir" data-v="${esc(g.pid)}"` : 'disabled'}><small>TRACK ${i + 1}</small><strong>${esc(g ? g.titulo : (i === list.length ? 'Guardar' : 'libre'))}</strong>${g ? `<span>${esc(g.sub || '')}</span>` : i === list.length ? '<span>al repetir un plan</span>' : ''}</button></li>`; }).join('')}</ul>${list.length ? '' : '<p class="t-caption-default" style="color:var(--color-text-secondary)">Cuando repitas un plan con un grupo, guárdalo aquí para volver a sintonizarlo en un toque.</p>'}</section>`,
  human: () => `<button class="s-human" data-act="humano"><span class="s-grip" aria-hidden="true"></span><span><strong>Habla con un humano</strong><small>Una persona del equipo responde</small></span></button>`,
  nav: cur => `<nav class="s-nav" aria-label="Principal">${[['Chats', 'chat', 'chats'], ['Mis sintonías', 'calendar', 'mis'], ['Perfil', 'users', 'perfil']].map(([t, i, v]) => `<button data-act="ir" data-v="${v}"${v === cur ? ' aria-current="page"' : ''}>${ic(i, 22)}${t}</button>`).join('')}</nav>`,
  btn: (t, act, v, style = 'primary', icn) => `<button class="s-button" data-style="${style}" data-block data-act="${act}" data-v="${esc(v || '')}">${icn ? ic(icn, 20) : ''}${esc(t)}</button>`,
  eyebrow: t => `<p class="s-eyebrow">${esc(t)}</p>`,
  empty: (t, b) => `<section class="s-empty">${av('estatica').replace('width="40" height="42"', 'width="96" height="96" style="border-radius:50%"')}<h3 class="t-heading-h3">${esc(t)}</h3><p class="t-body-small">${esc(b)}</p></section>`,
  composer: (chips, ph, dis, modo) => `<div class="s-composer">${chips && chips.length ? P.chips(chips) : ''}<form data-act="enviar"${modo ? ' data-sel' : ''}${modo === 'ok' ? ' data-ok' : ''}><input name="m" aria-label="Mensaje" placeholder="${esc(ph)}" autocomplete="off" maxlength="500"${dis ? ' disabled' : ''}><button class="s-send" aria-label="${modo === 'ok' ? 'OK, confirmar' : 'Enviar'}"${dis ? ' disabled' : ''}>${ic('arrow-right')}<span class="s-ok">OK</span></button></form></div>`,
};
